version: "3.8"

services:
  api-server:
    build: . # Runs Dockerfile defined for working_dir
    ports:
      - "3000:3000"
      - "9229:9229"
      - "9230:9230"
    volumes:
      - .:/app
      - /app/node_modules # Mount empty volume to prevent overrides
    working_dir: /app
    environment:
      - NODE_OPTIONS="--inspect=0.0.0.0:9229"
      - VALKEY_HOST=valkey # ???
    command: npm run dev
    depends_on:
      - valkey-db

  valkey-db:
    image: valkey/valkey:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
