declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_STRAVA_CLIENT_ID_TEST_ACCOUNT: string;
    NEXT_PUBLIC_STRAVA_CLIENT_ID_MAIN_ACCOUNT: string;
    STRAVA_CLIENT_SECRET_TEST_ACCOUNT: string;
    STRAVA_CLIENT_SECRET_MAIN_ACCOUNT: string;
    STRAVA_ACCESS_TOKEN_TEST_ACCOUNT: string;
    STRAVA_ACCESS_TOKEN_MAIN_ACCOUNT: string;
    STRAVA_SESSION_SECRET: string;
    NEXTAUTH_SECRET: string;
    NEXT_PUBLIC_WEBSITE_URL_TEST: string;
    NEXT_PUBLIC_WEBSITE_URL_PROD: string;
  }
}
