name: OpenAPI schema breaking changes analysis

on:
  push:
    branches:
      - "main"

jobs:
  oas-analysis:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: "24.4.1"
          # cache: "pnpm"
          # cache-dependency-path: "**/pnpm-lock.yaml"

      - name: 📥 Install Optic
        run: pnpm install -g @useoptic/optic

      - name: Run OAS analysis
        id: run_oas_analysis
        run: |
          OUTPUT=$(optic diff oas-schema-1.yml --base 9e5ff2d1 2>&1)
          ENCODED=$(echo "$OUTPUT" | base64 -w 0)
          echo "encoded_oas_analysis=$ENCODED" >> "$GITHUB_OUTPUT"

      - name: Output OAS Analysis
        env:
          encoded_oas_analysis: ${{ steps.run_oas_analysis.outputs.encoded_oas_analysis }}
        run: |
          echo "$encoded_oas_analysis" | base64 -d
