name: OpenAPI schema breaking changes analysis

on:
  push:
    branches:
      - "main"

jobs:
  oas-analysis:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: "20.9.0"

      - name: 📥 Install Optic
        run: npm install -g @useoptic/optic

      - name: Run OAS Analysis
        id: run_oas_analysis
        run: |
          # Run your Node script and capture output
          OUTPUT=$(optic diff oas-schema-1.yml oas-schema-2.yml)
          echo "output=$OUTPUT" >> $GITHUB_OUTPUT

      - name: Output OAS Analysis
        run: |
          echo ${{ steps.run_oas_analysis.outputs.output }}
